# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 737)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(size_policy)
        MainWindow.setMinimumSize(QtCore.QSize(683, 737))
        MainWindow.setMaximumSize(QtCore.QSize(683, 737))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 691, 738))
        self.tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_widget.setTabletTracking(False)
        self.tab_widget.setAcceptDrops(False)
        self.tab_widget.setAutoFillBackground(False)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setIconSize(QtCore.QSize(142, 25))
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setUsesScrollButtons(False)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(False)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.cam_tab = QtWidgets.QWidget()
        self.cam_tab.setObjectName("cam_tab")
        self.cam_image = QtWidgets.QLabel(self.cam_tab)
        self.cam_image.setGeometry(QtCore.QRect(20, 100, 640, 480))
        self.cam_image.setFrameShape(QtWidgets.QFrame.Panel)
        self.cam_image.setText("")
        self.cam_image.setObjectName("cam_image")
        self.status_bar_1 = QtWidgets.QLabel(self.cam_tab)
        self.status_bar_1.setGeometry(QtCore.QRect(20, 10, 640, 91))
        self.status_bar_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.status_bar_1.setText("")
        self.status_bar_1.setObjectName("status_bar_1")
        self.pushButton = QtWidgets.QPushButton(self.cam_tab)
        self.pushButton.setGeometry(QtCore.QRect(19, 578, 642, 80))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/realtime_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.cam_tab, icon1, "")
        self.record_tab = QtWidgets.QWidget()
        self.record_tab.setObjectName("record_tab")
        self.left_shift_button = QtWidgets.QPushButton(self.record_tab)
        self.left_shift_button.setGeometry(QtCore.QRect(232, 578, 216, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.left_shift_button.setFont(font)
        self.left_shift_button.setCheckable(False)
        self.left_shift_button.setDefault(False)
        self.left_shift_button.setObjectName("left_shift_button")
        self.ratio_button_1 = QtWidgets.QPushButton(self.record_tab)
        self.ratio_button_1.setGeometry(QtCore.QRect(19, 617, 215, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ratio_button_1.setFont(font)
        self.ratio_button_1.setCheckable(True)
        self.ratio_button_1.setDefault(False)
        self.ratio_button_1.setObjectName("ratio_button_1")
        self.picture_button = QtWidgets.QPushButton(self.record_tab)
        self.picture_button.setGeometry(QtCore.QRect(19, 578, 215, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.picture_button.setFont(font)
        self.picture_button.setCheckable(True)
        self.picture_button.setDefault(False)
        self.picture_button.setObjectName("picture_button")
        self.ratio_button_3 = QtWidgets.QPushButton(self.record_tab)
        self.ratio_button_3.setGeometry(QtCore.QRect(446, 617, 215, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ratio_button_3.setFont(font)
        self.ratio_button_3.setCheckable(True)
        self.ratio_button_3.setDefault(False)
        self.ratio_button_3.setObjectName("ratio_button_3")
        self.right_shift_buttopn = QtWidgets.QPushButton(self.record_tab)
        self.right_shift_buttopn.setGeometry(QtCore.QRect(446, 578, 215, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.right_shift_buttopn.setFont(font)
        self.right_shift_buttopn.setCheckable(False)
        self.right_shift_buttopn.setDefault(False)
        self.right_shift_buttopn.setObjectName("right_shift_buttopn")
        self.ratio_button_2 = QtWidgets.QPushButton(self.record_tab)
        self.ratio_button_2.setGeometry(QtCore.QRect(232, 617, 216, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ratio_button_2.setFont(font)
        self.ratio_button_2.setCheckable(True)
        self.ratio_button_2.setDefault(False)
        self.ratio_button_2.setObjectName("ratio_button_2")
        self.status_bar_2 = QtWidgets.QLabel(self.record_tab)
        self.status_bar_2.setGeometry(QtCore.QRect(20, 10, 640, 91))
        self.status_bar_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.status_bar_2.setText("")
        self.status_bar_2.setObjectName("status_bar_2")
        self.record_images = QtWidgets.QLabel(self.record_tab)
        self.record_images.setGeometry(QtCore.QRect(20, 100, 640, 480))
        self.record_images.setFrameShape(QtWidgets.QFrame.Panel)
        self.record_images.setText("")
        self.record_images.setObjectName("record_images")
        self.status_bar_2.raise_()
        self.record_images.raise_()
        self.ratio_button_1.raise_()
        self.left_shift_button.raise_()
        self.ratio_button_2.raise_()
        self.ratio_button_3.raise_()
        self.picture_button.raise_()
        self.right_shift_buttopn.raise_()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/ratio_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.record_tab, icon2, "")
        self.setting_tab = QtWidgets.QWidget()
        self.setting_tab.setObjectName("setting_tab")
        self.settingFrame = QtWidgets.QGroupBox(self.setting_tab)
        self.settingFrame.setGeometry(QtCore.QRect(20, 12, 640, 661))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settingFrame.setFont(font)
        self.settingFrame.setObjectName("settingFrame")
        self.ihunch_warn_set = QtWidgets.QGroupBox(self.settingFrame)
        self.ihunch_warn_set.setGeometry(QtCore.QRect(20, 30, 601, 81))
        self.ihunch_warn_set.setTitle("")
        self.ihunch_warn_set.setObjectName("ihunch_warn_set")
        self.ihunch_warn_button = QtWidgets.QPushButton(self.ihunch_warn_set)
        self.ihunch_warn_button.setGeometry(QtCore.QRect(460, 30, 129, 21))
        self.ihunch_warn_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/off_button_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("resource/on_button_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ihunch_warn_button.setIcon(icon3)
        self.ihunch_warn_button.setIconSize(QtCore.QSize(131, 31))
        self.ihunch_warn_button.setCheckable(True)
        self.ihunch_warn_button.setChecked(True)
        self.ihunch_warn_button.setObjectName("ihunch_warn_button")
        self.ihunch_warn_title = QtWidgets.QLabel(self.ihunch_warn_set)
        self.ihunch_warn_title.setGeometry(QtCore.QRect(20, 12, 191, 21))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ihunch_warn_title.setFont(font)
        self.ihunch_warn_title.setObjectName("ihunch_warn_title")
        self.ihunch_warn_comment = QtWidgets.QLabel(self.ihunch_warn_set)
        self.ihunch_warn_comment.setGeometry(QtCore.QRect(20, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ihunch_warn_comment.setFont(font)
        self.ihunch_warn_comment.setObjectName("ihunch_warn_comment")
        self.ratio_alarm_set = QtWidgets.QGroupBox(self.settingFrame)
        self.ratio_alarm_set.setGeometry(QtCore.QRect(20, 140, 601, 81))
        self.ratio_alarm_set.setTitle("")
        self.ratio_alarm_set.setObjectName("ratio_alarm_set")
        self.ratio_alarm_button = QtWidgets.QPushButton(self.ratio_alarm_set)
        self.ratio_alarm_button.setGeometry(QtCore.QRect(460, 30, 129, 21))
        self.ratio_alarm_button.setText("")
        self.ratio_alarm_button.setIcon(icon3)
        self.ratio_alarm_button.setIconSize(QtCore.QSize(131, 31))
        self.ratio_alarm_button.setCheckable(True)
        self.ratio_alarm_button.setChecked(True)
        self.ratio_alarm_button.setObjectName("ratio_alarm_button")
        self.ratio_alarm_comment = QtWidgets.QLabel(self.ratio_alarm_set)
        self.ratio_alarm_comment.setGeometry(QtCore.QRect(20, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ratio_alarm_comment.setFont(font)
        self.ratio_alarm_comment.setObjectName("ratio_alarm_comment")
        self.ratio_alarm_title = QtWidgets.QLabel(self.ratio_alarm_set)
        self.ratio_alarm_title.setGeometry(QtCore.QRect(20, 12, 191, 21))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ratio_alarm_title.setFont(font)
        self.ratio_alarm_title.setObjectName("ratio_alarm_title")
        self.alarm_cycle = QtWidgets.QComboBox(self.ratio_alarm_set)
        self.alarm_cycle.setGeometry(QtCore.QRect(360, 30, 76, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.alarm_cycle.setFont(font)
        self.alarm_cycle.setObjectName("alarm_cycle")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.setItemText(4, "")
        self.record_set = QtWidgets.QGroupBox(self.settingFrame)
        self.record_set.setGeometry(QtCore.QRect(20, 250, 601, 81))
        self.record_set.setTitle("")
        self.record_set.setObjectName("record_set")
        self.record_button = QtWidgets.QPushButton(self.record_set)
        self.record_button.setGeometry(QtCore.QRect(460, 30, 129, 21))
        self.record_button.setText("")
        self.record_button.setIcon(icon3)
        self.record_button.setIconSize(QtCore.QSize(131, 31))
        self.record_button.setCheckable(True)
        self.record_button.setChecked(True)
        self.record_button.setObjectName("record_button")
        self.record_comment = QtWidgets.QLabel(self.record_set)
        self.record_comment.setGeometry(QtCore.QRect(20, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.record_comment.setFont(font)
        self.record_comment.setObjectName("record_comment")
        self.record_title = QtWidgets.QLabel(self.record_set)
        self.record_title.setGeometry(QtCore.QRect(20, 12, 191, 21))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.record_title.setFont(font)
        self.record_title.setObjectName("record_title")
        self.record_cycle = QtWidgets.QComboBox(self.record_set)
        self.record_cycle.setGeometry(QtCore.QRect(360, 30, 76, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.record_cycle.setFont(font)
        self.record_cycle.setObjectName("record_cycle")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.set_reset_button = QtWidgets.QDialogButtonBox(self.settingFrame)
        self.set_reset_button.setGeometry(QtCore.QRect(460, 400, 156, 23))
        self.set_reset_button.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Reset)
        self.set_reset_button.setObjectName("set_reset_button")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.setting_tab, icon4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Turtleneck"))
        self.pushButton.setText(_translate("MainWindow", "시작"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.cam_tab), _translate("MainWindow", "실시간 화면"))
        self.left_shift_button.setText(_translate("MainWindow", "<<<"))
        self.ratio_button_1.setText(_translate("MainWindow", "통계1"))
        self.picture_button.setText(_translate("MainWindow", "사진"))
        self.ratio_button_3.setText(_translate("MainWindow", "통계3"))
        self.right_shift_buttopn.setText(_translate("MainWindow", ">>>"))
        self.ratio_button_2.setText(_translate("MainWindow", "통계2"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.record_tab), _translate("MainWindow", "거북목 통계"))
        self.settingFrame.setTitle(_translate("MainWindow", "설정"))
        self.ihunch_warn_title.setText(_translate("MainWindow", "거북목 경고"))
        self.ihunch_warn_comment.setText(_translate("MainWindow", "장시간 거북목을 유지할 경우 알림을 보내줍니다."))
        self.ratio_alarm_comment.setText(_translate("MainWindow", "일정 주기로 통계 알림을 보냅니다."))
        self.ratio_alarm_title.setText(_translate("MainWindow", "통계 알림"))
        self.alarm_cycle.setItemText(0, _translate("MainWindow", "10분"))
        self.alarm_cycle.setItemText(1, _translate("MainWindow", "20분"))
        self.alarm_cycle.setItemText(2, _translate("MainWindow", "30분"))
        self.alarm_cycle.setItemText(3, _translate("MainWindow", "1시간"))
        self.record_comment.setText(_translate("MainWindow", "일정 기간 동안의 거북목 사진 및 결과값을 기록합니다."))
        self.record_title.setText(_translate("MainWindow", "기록"))
        self.record_cycle.setItemText(0, _translate("MainWindow", "30분"))
        self.record_cycle.setItemText(1, _translate("MainWindow", "1시간"))
        self.record_cycle.setItemText(2, _translate("MainWindow", "2시간"))
        self.record_cycle.setItemText(3, _translate("MainWindow", "4시간"))
        self.record_cycle.setItemText(4, _translate("MainWindow", "6시간"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.setting_tab), _translate("MainWindow", "환경설정"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

