# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ihunch_layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 674)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 691, 675))
        self.tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab_widget.setFont(font)
        self.tab_widget.setTabletTracking(False)
        self.tab_widget.setAcceptDrops(False)
        self.tab_widget.setAutoFillBackground(False)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setIconSize(QtCore.QSize(116, 25))
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setUsesScrollButtons(False)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(False)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.cam_tab = QtWidgets.QWidget()
        self.cam_tab.setObjectName("cam_tab")
        self.cam_image = QtWidgets.QLabel(self.cam_tab)
        self.cam_image.setGeometry(QtCore.QRect(20, 100, 640, 480))
        #self.cam_image.setFrameShape(QtWidgets.QFrame.Panel)
        self.cam_image.setText("")
        self.cam_image.setObjectName("cam_image")
        self.status_bar_1 = QtWidgets.QLabel(self.cam_tab)
        self.status_bar_1.setGeometry(QtCore.QRect(20, 10, 640, 91))
        #self.status_bar_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.status_bar_1.setText("")
        self.status_bar_1.setObjectName("status_bar_1")
        self.video_button = QtWidgets.QPushButton(self.cam_tab)
        self.video_button.setGeometry(QtCore.QRect(19, 578, 642, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.video_button.setFont(font)
        self.video_button.setCheckable(True)
        self.video_button.setChecked(True)
        self.video_button.setFlat(True)
        self.video_button.setObjectName("video_button")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/realtime_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.cam_tab, icon1, "")
        self.record_tab = QtWidgets.QWidget()
        self.record_tab.setObjectName("record_tab")
        self.statistic_tab_widget = QtWidgets.QTabWidget(self.record_tab)
        self.statistic_tab_widget.setGeometry(QtCore.QRect(-2, -2, 691, 641))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statistic_tab_widget.setFont(font)
        self.statistic_tab_widget.setTabPosition(QtWidgets.QTabWidget.South)
        self.statistic_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.statistic_tab_widget.setIconSize(QtCore.QSize(166, 30))
        self.statistic_tab_widget.setObjectName("statistic_tab_widget")
        self.statistic_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statistic_1.setFont(font)
        self.statistic_1.setObjectName("statistic_1")
        self.status_bar_2 = QtWidgets.QLabel(self.statistic_1)
        self.status_bar_2.setGeometry(QtCore.QRect(20, 10, 640, 91))
        #self.status_bar_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.status_bar_2.setText("")
        self.status_bar_2.setStyleSheet("background-color: #f5f5f5")
        self.status_bar_2.setObjectName("status_bar_2")
        self.statistic_image_1 = QtWidgets.QLabel(self.statistic_1)
        self.statistic_image_1.setGeometry(QtCore.QRect(20, 100, 640, 480))
        #self.statistic_image_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.statistic_image_1.setText("")
        self.statistic_image_1.setStyleSheet("background-color: #f0f0f0")
        self.statistic_image_1.setObjectName("statistic_image_1")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/graph_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistic_tab_widget.addTab(self.statistic_1, icon2, "")
        self.statistic_2 = QtWidgets.QWidget()
        self.statistic_2.setObjectName("statistic_2")
        self.status_bar_3 = QtWidgets.QLabel(self.statistic_2)
        self.status_bar_3.setGeometry(QtCore.QRect(20, 10, 640, 91))
        #self.status_bar_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.status_bar_3.setText("")
        self.status_bar_3.setStyleSheet("background-color: #f5f5f5")
        self.status_bar_3.setObjectName("status_bar_3")
        self.statistic_image_2 = QtWidgets.QLabel(self.statistic_2)
        self.statistic_image_2.setGeometry(QtCore.QRect(20, 100, 640, 480))
        #self.statistic_image_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.statistic_image_2.setText("")
        self.statistic_image_2.setStyleSheet("background-color: #f0f0f0")
        self.statistic_image_2.setObjectName("statistic_image_2")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/graph_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistic_tab_widget.addTab(self.statistic_2, icon3, "")
        self.statistic_3 = QtWidgets.QWidget()
        self.statistic_3.setObjectName("statistic_3")
        self.statistic_image_3 = QtWidgets.QLabel(self.statistic_3)
        self.statistic_image_3.setGeometry(QtCore.QRect(20, 100, 640, 480))
        #self.statistic_image_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.statistic_image_3.setText("")
        self.statistic_image_3.setStyleSheet("background-color: #f0f0f0")
        self.statistic_image_3.setObjectName("statistic_image_3")
        self.status_bar_4 = QtWidgets.QLabel(self.statistic_3)
        self.status_bar_4.setGeometry(QtCore.QRect(20, 10, 640, 91))
        #self.status_bar_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.status_bar_4.setText("")
        self.status_bar_4.setStyleSheet("background-color: #f5f5f5")
        self.status_bar_4.setObjectName("status_bar_4")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/graph_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistic_tab_widget.addTab(self.statistic_3, icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/ratio_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.record_tab, icon5, "")
        self.picture = QtWidgets.QWidget()
        self.picture.setObjectName("picture")
        self.picture_ihunch_ratio = QtWidgets.QLabel(self.picture)
        self.picture_ihunch_ratio.setGeometry(QtCore.QRect(20, 10, 640, 91))
        #self.picture_ihunch_ratio.setFrameShape(QtWidgets.QFrame.Panel)
        self.picture_ihunch_ratio.setText("")
        self.picture_ihunch_ratio.setStyleSheet("background-color: #f5f5f5")
        self.picture_ihunch_ratio.setObjectName("picture_ihunch_ratio")
        self.picture_image = QtWidgets.QLabel(self.picture)
        self.picture_image.setGeometry(QtCore.QRect(20, 100, 640, 480))
        #self.picture_image.setFrameShape(QtWidgets.QFrame.Panel)
        self.picture_image.setText("")
        self.picture_image.setStyleSheet("background-color: #f0f0f0")
        self.picture_image.setObjectName("picture_image")
        self.left_shift_button = QtWidgets.QPushButton(self.picture)
        self.left_shift_button.setGeometry(QtCore.QRect(198, 583, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.left_shift_button.setFont(font)
        self.left_shift_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/left_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_shift_button.setIcon(icon6)
        self.left_shift_button.setIconSize(QtCore.QSize(50, 70))
        self.left_shift_button.setCheckable(False)
        self.left_shift_button.setDefault(False)
        self.left_shift_button.setFlat(True)
        self.left_shift_button.setObjectName("left_shift_button")
        self.right_shift_button = QtWidgets.QPushButton(self.picture)
        self.right_shift_button.setGeometry(QtCore.QRect(431, 583, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.right_shift_button.setFont(font)
        self.right_shift_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resource/right_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_shift_button.setIcon(icon7)
        self.right_shift_button.setIconSize(QtCore.QSize(50, 70))
        self.right_shift_button.setCheckable(False)
        self.right_shift_button.setDefault(False)
        self.right_shift_button.setFlat(True)
        self.right_shift_button.setObjectName("right_shift_button")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resource/picture_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.picture, icon8, "")
        self.setting_tab = QtWidgets.QWidget()
        self.setting_tab.setObjectName("setting_tab")
        self.settingFrame = QtWidgets.QGroupBox(self.setting_tab)
        self.settingFrame.setGeometry(QtCore.QRect(20, 12, 640, 607))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settingFrame.setFont(font)
        self.settingFrame.setObjectName("settingFrame")
        self.ihunch_warn_set = QtWidgets.QGroupBox(self.settingFrame)
        self.ihunch_warn_set.setGeometry(QtCore.QRect(20, 30, 601, 81))
        self.ihunch_warn_set.setTitle("")
        self.ihunch_warn_set.setObjectName("ihunch_warn_set")
        self.ihunch_warn_button = QtWidgets.QPushButton(self.ihunch_warn_set)
        self.ihunch_warn_button.setGeometry(QtCore.QRect(460, 30, 129, 21))
        self.ihunch_warn_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resource/off_button_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap("resource/on_button_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ihunch_warn_button.setIcon(icon9)
        self.ihunch_warn_button.setIconSize(QtCore.QSize(131, 31))
        self.ihunch_warn_button.setCheckable(True)
        self.ihunch_warn_button.setChecked(True)
        self.ihunch_warn_button.setObjectName("ihunch_warn_button")
        self.ihunch_warn_title = QtWidgets.QLabel(self.ihunch_warn_set)
        self.ihunch_warn_title.setGeometry(QtCore.QRect(20, 12, 191, 21))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ihunch_warn_title.setFont(font)
        self.ihunch_warn_title.setObjectName("ihunch_warn_title")
        self.ihunch_warn_comment = QtWidgets.QLabel(self.ihunch_warn_set)
        self.ihunch_warn_comment.setGeometry(QtCore.QRect(20, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ihunch_warn_comment.setFont(font)
        self.ihunch_warn_comment.setObjectName("ihunch_warn_comment")
        self.statistic_alarm_set = QtWidgets.QGroupBox(self.settingFrame)
        self.statistic_alarm_set.setGeometry(QtCore.QRect(20, 140, 601, 81))
        self.statistic_alarm_set.setTitle("")
        self.statistic_alarm_set.setObjectName("statistic_alarm_set")
        self.statistic_alarm_button = QtWidgets.QPushButton(self.statistic_alarm_set)
        self.statistic_alarm_button.setGeometry(QtCore.QRect(460, 30, 129, 21))
        self.statistic_alarm_button.setText("")
        self.statistic_alarm_button.setIcon(icon9)
        self.statistic_alarm_button.setIconSize(QtCore.QSize(131, 31))
        self.statistic_alarm_button.setCheckable(True)
        self.statistic_alarm_button.setChecked(True)
        self.statistic_alarm_button.setObjectName("statistic_alarm_button")
        self.statistic_alarm_button.toggled.connect(self.alarm_cycle_toggle)
        self.statistic_alarm_comment = QtWidgets.QLabel(self.statistic_alarm_set)
        self.statistic_alarm_comment.setGeometry(QtCore.QRect(20, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.statistic_alarm_comment.setFont(font)
        self.statistic_alarm_comment.setObjectName("statistic_alarm_comment")
        self.statistic_alarm_title = QtWidgets.QLabel(self.statistic_alarm_set)
        self.statistic_alarm_title.setGeometry(QtCore.QRect(20, 12, 191, 21))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statistic_alarm_title.setFont(font)
        self.statistic_alarm_title.setObjectName("statistic_alarm_title")
        self.alarm_cycle = QtWidgets.QComboBox(self.statistic_alarm_set)
        self.alarm_cycle.setGeometry(QtCore.QRect(360, 30, 76, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.alarm_cycle.setFont(font)
        self.alarm_cycle.setObjectName("alarm_cycle")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.addItem("")
        self.alarm_cycle.setItemText(4, "")
        self.record_set = QtWidgets.QGroupBox(self.settingFrame)
        self.record_set.setGeometry(QtCore.QRect(20, 250, 601, 81))
        self.record_set.setTitle("")
        self.record_set.setObjectName("record_set")
        self.record_button = QtWidgets.QPushButton(self.record_set)
        self.record_button.setGeometry(QtCore.QRect(460, 30, 129, 21))
        self.record_button.setText("")
        self.record_button.setIcon(icon9)
        self.record_button.setIconSize(QtCore.QSize(131, 31))
        self.record_button.setCheckable(True)
        self.record_button.setChecked(True)
        self.record_button.setObjectName("record_button")
        self.record_button.toggled.connect(self.record_cycle_toggle)
        self.record_comment = QtWidgets.QLabel(self.record_set)
        self.record_comment.setGeometry(QtCore.QRect(20, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.record_comment.setFont(font)
        self.record_comment.setObjectName("record_comment")
        self.record_title = QtWidgets.QLabel(self.record_set)
        self.record_title.setGeometry(QtCore.QRect(20, 12, 191, 21))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.record_title.setFont(font)
        self.record_title.setObjectName("record_title")
        self.record_cycle = QtWidgets.QComboBox(self.record_set)
        self.record_cycle.setGeometry(QtCore.QRect(360, 30, 76, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.record_cycle.setFont(font)
        self.record_cycle.setObjectName("record_cycle")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.record_cycle.addItem("")
        self.reset_button = QtWidgets.QPushButton(self.settingFrame)
        self.reset_button.setGeometry(QtCore.QRect(460, 400, 75, 23))
        self.reset_button.setObjectName("reset_button")
        self.reset_button.clicked.connect(self.return_initial_setting)
        self.apply_button = QtWidgets.QPushButton(self.settingFrame)
        self.apply_button.setGeometry(QtCore.QRect(540, 400, 75, 23))
        self.apply_button.setObjectName("apply_button")
        self.apply_button.clicked.connect(self.apply_current_setting)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resource/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.setting_tab, icon10, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.statistic_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Turtleneck"))
        self.video_button.setText(_translate("MainWindow", "일시 정지"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.cam_tab), _translate("MainWindow", "카메라"))
        self.statistic_tab_widget.setTabText(self.statistic_tab_widget.indexOf(self.statistic_1), _translate("MainWindow", "통계 1"))
        self.statistic_tab_widget.setTabText(self.statistic_tab_widget.indexOf(self.statistic_2), _translate("MainWindow", "통계 2"))
        self.statistic_tab_widget.setTabText(self.statistic_tab_widget.indexOf(self.statistic_3), _translate("MainWindow", "통계 3"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.record_tab), _translate("MainWindow", "통계"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.picture), _translate("MainWindow", "사진"))
        self.settingFrame.setTitle(_translate("MainWindow", "설정"))
        self.ihunch_warn_title.setText(_translate("MainWindow", "거북목 경고"))
        self.ihunch_warn_comment.setText(_translate("MainWindow", "장시간 거북목을 유지할 경우 알림을 보내줍니다."))
        self.statistic_alarm_comment.setText(_translate("MainWindow", "일정 주기로 통계 알림을 보냅니다."))
        self.statistic_alarm_title.setText(_translate("MainWindow", "통계 알림"))
        self.alarm_cycle.setItemText(0, _translate("MainWindow", "10분"))
        self.alarm_cycle.setItemText(1, _translate("MainWindow", "20분"))
        self.alarm_cycle.setItemText(2, _translate("MainWindow", "30분"))
        self.alarm_cycle.setItemText(3, _translate("MainWindow", "1시간"))
        self.record_comment.setText(_translate("MainWindow", "일정 기간 동안의 거북목 사진 및 결과값을 기록합니다."))
        self.record_title.setText(_translate("MainWindow", "기록"))
        self.record_cycle.setItemText(0, _translate("MainWindow", "30분"))
        self.record_cycle.setItemText(1, _translate("MainWindow", "1시간"))
        self.record_cycle.setItemText(2, _translate("MainWindow", "2시간"))
        self.record_cycle.setItemText(3, _translate("MainWindow", "4시간"))
        self.record_cycle.setItemText(4, _translate("MainWindow", "6시간"))
        self.reset_button.setText(_translate("MainWindow", "초기화"))
        self.apply_button.setText(_translate("MainWindow", "적용"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.setting_tab), _translate("MainWindow", "설정"))

    #통계 알림 on, off시 발생되는 이벤트
    def alarm_cycle_toggle(self, state):
        self.alarm_cycle.setDisabled({True:False, False:True}[state])

    #기록 알림 on, off 시 발생되는 이벤트
    def record_cycle_toggle(self, state):
        self.record_cycle.setDisabled({True:False, False:True}[state])

    #초기 설정 값 저장
    def apply_current_setting(self):
        self.now_warning_alarm = self.ihunch_warn_button.isChecked()
        self.now_statistic_alarm = self.statistic_alarm_button.isChecked()
        self.now_statistic_cycle = self.alarm_cycle.currentIndex()
        self.now_record = self.record_button.isChecked()
        self.now_record_cycle = self.record_cycle.currentIndex()

    #저장되지 않은 설정 값 삭제
    def return_current_setting(self):
        self.ihunch_warn_button.setChecked(self.now_warning_alarm)
        self.alarm_cycle.setCurrentIndex(self.now_statistic_cycle)
        self.statistic_alarm_button.setChecked(self.now_statistic_alarm)
        self.record_cycle.setCurrentIndex(self.now_record_cycle)
        self.record_button.setChecked(self.now_record)

    #설정 값 초기화
    def return_initial_setting(self):
        self.ihunch_warn_button.setChecked(True)
        self.alarm_cycle.setCurrentIndex(0)
        self.statistic_alarm_button.setChecked(True)
        self.record_cycle.setCurrentIndex(0)
        self.record_button.setChecked(True)

    #video_button on, off 설정
    def video_on_off(self, state):
        if state:
            self.video_button.setText("일시 정지")
        else:
            self.video_button.setText("시작")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

